export const GET_DIAMOND_PLAN = "GET_DIAMOND_PLAN";
export const CREATE_NEW_DIAMOND_PLAN = "CREATE_NEW_DIAMOND_PLAN";
export const EDIT_DIAMOND_PLAN = "EDIT_DIAMOND_PLAN";
export const DELETE_DIAMOND_PLAN = "DELETE_DIAMOND_PLAN";

export const OPEN_DIAMOND_PLAN_DIALOG = "OPEN_DIAMOND_PLAN_DIALOG";
export const CLOSE_DIAMOND_PLAN_DIALOG = "CLOSE_DIAMOND_PLAN_DIALOG";

// export const GET_COIN_PLAN_HISTORY = "GET_COIN_PLAN_HISTORY";
