export const GET_REDEEM_PLAN = "GET_REDEEM_PLAN";
export const CREATE_NEW_REDEEM_PLAN = "CREATE_NEW_REDEEM_PLAN";
export const EDIT_REDEEM_PLAN = "EDIT_REDEEM_PLAN";
export const DELETE_REDEEM_PLAN = "DELETE_REDEEM_PLAN";

export const OPEN_REDEEM_PLAN_DIALOG = "OPEN_REDEEM_PLAN_DIALOG";
export const CLOSE_REDEEM_PLAN_DIALOG = "CLOSE_REDEEM_PLAN_DIALOG";
